//
//  RegisterRouter.swift
//  Arquiteturas
//
//  Created by Felipe Augusto Correia on 23/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
  func routeToHome()
}

protocol RegisterDataPassing
{
  var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
  weak var viewController: RegisterViewController?
  var dataStore: RegisterDataStore?
  
  // MARK: Routing
  
    func routeToHome() {
        let destinationVC = HomeViewController()
        navigateToPush(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
    
    func navigateToPush(source: RegisterViewController, destination: UIViewController)
    {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
  
  //func navigateToSomewhere(source: RegisterViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: RegisterDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
